name: Continuous Deployment

on:
  push:
    branches: [main]

jobs:
  ci:
    name: Continuous Integration
    uses: ./.github/workflows/shared.yaml
    secrets: inherit

  deploy:
    name: Deploy to npmjs.org
    if: "!contains(github.event.head_commit.message, '[skip deploy]')"
    runs-on: ubuntu-latest
    needs: ci
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-22
          path: dist
      - name: Publish to npm
        run: |
          pnpm publish ./dist --access public --tag pre;
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
